# File to install packages in AWS

install.packages("lubridate")
install.packages("sqldf")
install.packages("data.table")
install.packages("bit64")
install.packages("digest")
install.packages("caret")
install.packages("zoo")
install.packages("plyr")
install.packages("randomForest")
install.packages("xgboost")
install.packages("RPushbullet")
install.packages("tm")
install.packages("SnowballC")
install.packages("caretEnsemble")
install.packages("pROC")
install.packages("glmnet")
install.packages("e1071")
install.packages("Rtsne")
install.packages("dplyr")
install.packages("doParallel")
install.packages("readr")
